### PR TITLE
Timezone support

### PR DESCRIPTION
**Pull request by rxaviers**
Checklist:
- [x] Implementation
- [x] Tests
- [x] Documentation

### CODE REVIEW

**Comment by rxaviers** [comment]
This change allows things like:
```js
import ianaTzData from "iana-tz-data";

sinon.useFakeTimers(new Date("2016-04-10 12:00:00").getTime());

// Target: 2016-04-09 17:00:00 GMT-7 (PDT)
// Now: 2016-04-10 05:00:00 GMT-7 (PDT)
expect(relativeTime.format(new Date("2016-04-10T00:00:00Z"), {
  timeZoneData: ianaTzData.zoneData.America.Los_Angeles
})).to.equal("yesterday");

// Target: 2016-04-10 14:00:00 GMT+2 (Central European Summer Time)
// Now: 2016-04-10 14:00:00 GMT+2 (Central European Summer Time)
expect(relativeTime.format(new Date("2016-04-10T00:00:00Z"), {
  timeZoneData: ianaTzData.zoneData.Europe.Berlin
})).to.equal("12 hours ago");
```

**Comment by jzaefferer** [comment]
Seems like most of the implementation here is actually inside https://github.com/rxaviers/zoned-date-time which is lacking tests and docs (as well). Should I review that as well? Since everything there is already in master, its harder to do a proper review.

In both cases, docs would help to understand how they're supposed to be used. For relative-time, is there more than the sample above?

**Comment by rxaviers** [comment]
> Seems like most of the implementation here is actually inside https://github.com/rxaviers/zoned-date-time which is lacking tests and docs (as well). Should I review that as well? Since everything there is already in master, its harder to do a proper review.

Docs updated there. :)

**Comment by rxaviers** [comment]
> In both cases, docs would help to understand how they're supposed to be used

Docs here (in this PR) have been updated too.

**Comment by rxaviers** [comment]
> For relative-time, is there more than the sample above?

[Tests](https://github.com/rxaviers/relative-time/pull/4/files#diff-c9ad6794621c91966d39f8fe4094ccf2R149) and the just included docs.

**Pull request merged**
